tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
brew "git"
brew "starship"
brew "yarn"
brew "vips"
# brew "nvm"
cask "figma"
cask "hyper"
cask "dash"
cask "insomnia"
cask "logitech-options"
cask "microsoft-teams"
cask "slack"
cask "visual-studio-code"
cask "webstorm"
