command_timeout = 2000

[aws]
disabled = true

[directory]
style = "blue bold"

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
ahead = "🏎💨↑$count"
behind = "😰↓$count"
conflicted = "🏳"
deleted = "💩"
disabled = false
diverged = "😵↑$ahead_count↓$behind_count"
format = "$all_status$ahead_behind "
modified = "💩"
renamed = "💩"
staged = "💩"
stashed = ""
untracked = "💩"
up_to_date = "✅"

[hostname]
disabled = true

[kubernetes]
disabled = false

[package]
disabled = true

[username]
disabled = true
