link:
	stow agents
	stow bin
	stow claude
	stow direnv
	stow ghostty
	stow git
	stow k9s
	stow nvim
	stow starship
	stow streamdeck
	stow television
	stow zsh

unlink:
	stow -D agents
	stow -D bin
	stow -D claude
	stow -D direnv
	stow -D ghostty
	stow -D git
	stow -D k9s
	stow -D nvim
	stow -D starship
	stow -D streamdeck
	stow -D television
	stow -D zsh