link:
	stow bin
	stow direnv
	stow ghostty
	stow k9s
	stow nvim
	stow starship
	stow streamdeck
	stow zsh

unlink: 
	stow -D bin
	stow -D direnv
	stow -D ghostty
	stow -D k9s
	stow -D nvim
	stow -D starship
	stow -D streamdeck
	stow -D zsh