k9s:
  cluster: intrum-stacc-dev-aks
  namespace:
    active: intrum-dev-1
    lockFavorites: false
    favorites:
      - intrum-dev-1
  view:
    active: v1/pods
  featureGates:
    nodeShell: false
  proxy: null
