k9s:
  cluster: intrum-stacc-dev-aks
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - intrum-dev-1
  view:
    active: pods all
  featureGates:
    nodeShell: false
  proxy: null
